"""
String matching utilities for Prefix-Matching in constrained decoding.
"""

from typing import List, Tuple


def calculate_remainder(curr_txt: str, cible: str) -> Tuple[str, int]:
    """
    Determines the exact suffix of the target string that remains to be
    generated by finding the maximum overlap with the current text.
    """
    rest_to_write = cible
    max_size = len(cible)
    for i in range(max_size, 0, -1):
        if curr_txt.endswith(rest_to_write[:i]):
            return rest_to_write[i:], i
    return cible, 0


def get_remainder(curr_txt: str, cibles: List[str]) -> List[Tuple[str, int]]:
    """
    Evaluates a list of target strings to find their respective remainders
    and overlap scores against the currently generated text.
    """
    potential_remainders = []
    for cible in cibles:
        remainder, score = calculate_remainder(curr_txt, cible)
        potential_remainders.append((remainder, score))
    return potential_remainders
